### ISSUE TITLE
Feature-request: a command to delete a bil

### ISSUE THREAD

**Issue by kritixilithos** [fergusq/bilar#2]
I've seen `autoremove`, but that doesn't allow the user to choose which files they want to remove. So my idea is that something like `bilar remove a_bil_package` would remove `a_bil_package` from the system.

**Comment by kritixilithos** [comment]
I've come upon the need for such a command after experimenting with a bil I made. I tested my bil and installed it using bilar (I've updated updated my tar since the other issue). After finding a bug, I fixed it, and tried to `bilar install` again, however bilar replied with a `Bil XXX is already installed`.

**Comment by fergusq** [comment]
I will implement this, but I recommend you to use release candidate versions (like `1.0.0-rc.1`) instead of removing and installing a bil with same version number but different content. You can use autoremove to delete these after creating a new version. This ensures that there are no conflicting packages in the system.

**Comment by fergusq** [comment]
The new version of bilar uses a different `.bilar/db.pmf` format, so you should delete it before updating.
